#-------------------------------
# Site Settings
title: Motoko's Blog
logo:  # You can add own logo. For example '/images/logo.png'.
description: マイクラと学びをテーマに書いているブログです。 #Hilton is a super simple portfolio theme for Jekyll.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'ホーム'
      url: '/'
    - title: 'コラム'
      url: '/projects/'
    - title: '体験ログ'
      url: '/blog/'
    - title: 'その他'
      submenu:
      - url: '/about/'
        title: 'About'
      - url: '/contact/'
        title: 'Contact'
      - url: '/PrivacyPolicy/'
        title: 'Privacy Policy'
      - url: '/gallery/'
        title: 'Gallery'

#-------------------------------
# Author Settings
author:
  author__name: Motoko
  author__bio: アフタースクールで理科講師をしていました。日常の生活の中で色々なものに興味を持ち、探求する楽しさを子どもたちに伝えていければいいなと思っています。2児の母、Minecraft certified teacher badge取得。
  author__avatar: '/images/01-1.jpg'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/motonomotoko"}
# - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# - {icon: "ion-logo-instagram", link: "https://instagram.com"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# - {icon: "ion-logo-github", link: "https://github.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: Come to play Minecraft!! #I'm Monica. I will create design that can give you value
  hero__description: このブログでは、マイクラを使った学びの可能性に興味を持った筆者が、実際に調べたり、遊んだりした内容を綴っています。
  hero__image: '/images/01.jpg'


#-------------------------------
# Newsletter
mailchimp: #enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Your email address...
mailchimp__button__text: Get updates


#-------------------------------
# Projects Settings
projects__settings:
  projects__title: コラム
  projects__description: マイクラと教育に関する話題や、遊ぶ上で感じた疑問や感想をまとめています。

#-------------------------------
# Blog Section
blog__settings:
  blog__title: 体験ログ
  blog__description: インストール方法や子どもたちと遊んだ内容まで、実際のアクティビティ内容を、手順も含めてまとめています。


#-------------------------------
# Gallery Footer Settings
gallery:
  gallery__images:
    - alt: 'Rest'
      url: '/images/gallery-1.jpg'
    - alt: 'Lifestyle'
      url: '/images/gallery-2.jpg'
    - alt: 'Hobby'
      url: '/images/gallery-3.jpg'
    - alt: 'Notes'
      url: '/images/gallery-4.jpg'


#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'ホーム'
      url: '/'
    - title: 'コラム'
      url: '/projects/'
    - title: '体験ログ'
      url: '/blog/'
    - url: '/about/'
      title: 'About'
    - url: '/contact/'
      title: 'Contact'
    - url: '/PrivacyPolicy/'
      title: 'Privacy Policy'
    - url: '/gallery/'
      title: 'Gallery'


#-------------------------------
# Contact Settings
contact:
  email: https://formspree.io/f/xpzeoobj # Add your form_id
  description: 当サイトをご訪問いただきありがとうございます。ご質問、ご指摘などございましたら下記フォームからお気軽にお問い合わせください。

# NOTE
# Hilton theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-52TLL35C0R # Add your GA Tracking Id
